### ISSUE TITLE
总是0 user deleted，客户端无法使用

### ISSUE THREAD

**Issue by jack338c** [XrayR-project/XrayR-release#10]
大神好！
昨天晚上用前端sspanel uim配合XrayR的Docker compose 安装方式成功连接，无论openwrt端还是PC qv2ray端，速度都很爽！
测试过程中，在openwrt路由器切换xtls-rprx-direct和xtls-rprx-splice之间时，突然用不了，24小时内苦苦排查，用不同vps啥的，时间也调整了，防火墙也打开并放行各种端口，还是未解决，目前无能为力，只好来找您了

刚刚换用一键方式装了，以下是log信息,总是0 user deleted，不知道应该从哪个方向入手去解决？
Mar 09 06:10:25 vm21995.akkocloud.com XrayR[4029]: 2022/03/09 06:10:25 [NodeID: 2] 0 user deleted, 0 user added
Mar 09 06:11:26 vm21995.akkocloud.com XrayR[4029]: 2022/03/09 06:11:26 [dmt1.top] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal.
Mar 09 06:11:26 vm21995.akkocloud.com XrayR[4029]: 2022/03/09 06:11:26 [NodeID: 2] Added 1 new users
Mar 09 06:11:26 vm21995.akkocloud.com XrayR[4029]: 2022/03/09 06:11:26 [NodeID: 2] 0 user deleted, 1 user added

**Comment by RManLuo** [comment]
xtls只支持xtls-rprx-direct流控，更多信息请将日志等级调至debug显示。

**Comment by jack338c** [comment]
@RManLuo  谢谢回复
是XrayR log debug 这样命令吗？

**Comment by RManLuo** [comment]
> @RManLuo 谢谢回复 是XrayR log debug 这样命令吗？

https://crackair.gitbook.io/xrayr-project/xrayr-pei-zhi-wen-jian-shuo-ming/config#ri-zhi-pei-zhi

**Comment by jack338c** [comment]
@RManLuo非常感谢！

**Comment by jack338c** [comment]
@RManLuo 
大神，一键安装logdebug 级别和Docker compose 安装方式的log输出一样的,请看附上的图片，不知道这个是客户端问题，还是前端问题（如果是后者，我该从哪个方向排除？）
![Screen Shot 2022-03-09 at 1 17 38 PM](https://user-images.githubusercontent.com/10782586/157378342-a1fc97e2-0859-4535-8a66-fa5336e538a9.png)

**Comment by RManLuo** [comment]
一开始已经添加了2个新用户，后续只会在用户信息变化时增量增加，由于用户信息不变，所以后续新增用户都是0。关于，连接不上问题，请仔细检查客户端协议配置信息和订阅一致。启用vless和xtls需要同时在后端配置文件中修改。https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/v2ray#qi-yong-vless
https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/v2ray#qi-yong-xtls

**Comment by jack338c** [comment]
@RManLuo 
谢谢耐心指导，成功了！
太感谢了，世界因你而美好！ 🥂

**Comment by jack338c** [comment]
大神好！今天用新版的SSPanel uim+XrayR一键脚本后端搭了下，一直连不上
然后按照你的说明教程试图找解决办法，几个点一直没搞明白
1 这个SSPanel Custom Config是在前端吗，去目录文件还是网页界面红色圈地方处修改？（请看附上图片）
2 ApiConfig中将DisableCustomConfig设为true，这个ApiConfig我在config.yml中找到了，但是并没有DisableCustomConfig设为true点选项
![Screen Shot 2022-03-10 at 10 32 30 PM](https://user-images.githubusercontent.com/10782586/157685342-48948b0a-6780-4858-992d-b8645d06810f.png)

对接新版SSPanel Custom Config
对于sspanel >= 2021.11的版本中自动启用Custom_config的配置方法，请查看以下配置，正确配置结点信息。关于订阅相关信息，请查看SSPanel相关文档：https://wiki.sspanel.org/#/universal-subscription。 如果不想使用custom config，请在ApiConfig中将DisableCustomConfig设为true。

ApiConfig
PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, , Proxypanel
    ApiConfig:

**Comment by jack338c** [comment]
@RManLuo 
大神，另外请问下，用Docker compose 安装方式时，/var/lib/docker/containers/下面有很大的log文件产生，请问这个可以关闭，或者限制log大小吗？
还有，一键方式安装的log文件目录是在/etc/XrayR/吗，debug级别时运行好像没看到产生文件

**Comment by jack338c** [comment]
@RManLuo 大神好，新版SSPanel Custom Config的问题跳过了，不去研究了
方便时请帮我解答最后的log问题
