### ISSUE TITLE
获取uuid失败

### ISSUE THREAD

**Issue by cwv587** [XrayR-project/XrayR-release#2]
y/vmess: Not Found
4月 30 03:40:40 humor16875 XrayR[8810]: 2021/04/30 03:40:40 [Info] [964238645] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from 1.86.18.117:33130 > proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
4月 30 03:40:40 humor16875 XrayR[8810]: 2021/04/30 03:40:40 [Info] [964238645] app/proxyman/inbound: failed to close connection > transport/internet/websocket: failed to close connection > transport/internet/websocket: websocket: close sent
4月 30 03:40:40 humor16875 XrayR[8810]: 2021/04/30 03:40:40 1.86.18.117:33130 rejected  proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
4月 30 03:40:40 humor16875 XrayR[8810]: 2021/04/30 03:40:40 Panel Start fialed: proxy/vmess: failed to parse ID > invalid UUID: 545f75d11f233845bd7fb7bd0f83e52fd3b0c69aafae3e8378f19109cb409fd8
4月 30 03:40:40 humor16875 XrayR[8810]: panic: Panel Start fialed: proxy/vmess: failed to parse ID > invalid UUID: 545f75d11f233845bd7fb7bd0f83e52fd3b0c69aafae3e8378f19109cb409fd8
4月 30 03:40:40 humor16875 XrayR[8810]: goroutine 1 [running]:
4月 30 03:40:40 humor16875 XrayR[8810]: log.Panicf(0x1d0bf47, 0x16, 0xc00087fea0, 0x1, 0x1)
4月 30 03:40:40 humor16875 XrayR[8810]: log/log.go:361 +0xc5
4月 30 03:40:40 humor16875 XrayR[8810]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000489ac0)
4月 30 03:40:40 humor16875 XrayR[8810]: github.com/XrayR-project/XrayR/panel/panel.go:118 +0x551
4月 30 03:40:40 humor16875 XrayR[8810]: main.main()
4月 30 03:40:40 humor16875 XrayR[8810]: github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5
4月 30 03:40:40 humor16875 systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
4月 30 03:40:40 humor16875 systemd[1]: Unit XrayR.service entered failed state.
4月 30 03:40:40 humor16875 systemd[1]: XrayR.service failed.

**Comment by crackair** [comment]
uuid格式不对，建议检查前端数据库
