### ISSUE TITLE
昨天开始出现这个错误

### ISSUE THREAD

**Issue by wxfyes** [XrayR-project/XrayR-release#6]
xrayr_1  | panic: Panel Start fialed: request https://yuming.com/api/v1/server/ShadowsocksTidalab/user failed: Get "https://yuming.com/api/v1/server/ShadowsocksTidalab/user?key=miyao123&local_port=1&node_id=27&token=miyao123": dial tcp: lookup https://yuming.com on 169.254.169.254:53: server misbehaving
xrayr_1  | 
xrayr_1  | goroutine 1 [running]:
xrayr_1  | log.Panicf(0x1863782, 0x16, 0x40005bfe88, 0x1, 0x1)
xrayr_1  |      log/log.go:361 +0xa8
xrayr_1  | github.com/XrayR-project/XrayR/panel.(*Panel).Start(0x4000317b40)
xrayr_1  |      github.com/XrayR-project/XrayR/panel/panel.go:137 +0x62c
xrayr_1  | main.main()
xrayr_1  |      github.com/XrayR-project/XrayR/main/main.go:85 +0x1a8

**Comment by wxfyes** [comment]
看着好像是解析出问题了？难道是和cloudflare的CDN有关？但用soga启动有一切正常

**Comment by RManLuo** [comment]
与后端无关，请自己排查。
