### ISSUE TITLE
出现VMessAEAD

### ISSUE THREAD

**Issue by jiangjk2000** [XrayR-project/XrayR-release#7]
2022/01/02 22:36:31 XX.XX.XX.XX:XX rejected  proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable xray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.

docker-compose中添加environment 'V2RAY_VMESS_AEAD_FORCED=false'无效，本机环境添加也无效，求解决

**Comment by GZ1903** [comment]
> 

你可以相对应的在前端面板进行修改，将节点的AlterID改为0，重新对接，可以解决该问题。
